<HEAD>
<title>NEW USER SIGNUP</title>
</HEAD>


<?php


include "db_connect.php";

?>

<form action="add_login.PHP" AUTOCOMPLETE="OFF">
 <body background="lap.png"> 

 <h1><center><br><br><br><br><br><p style="color:#0000A0" >ENTER YOUR NEW DATA</p></center></h1>
  <h3><center>PHONE NUMBER &nbsp: &nbsp <input type="bigint"  name="PHONENUMBER" placeholder="eg: 857XXXX356" style="text-align: center; outline-color: #5050FF"> </center>
  <center>(Enter 10 digit number)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;</center><br>
<center>YOUR PASSCODE &nbsp: &nbsp <input type="password"  name="PASSWORD" placeholder="eg: 56XXXX56" style="text-align: center; outline-color: #5050FF"> </center>
<center>(Enter 8 digit number)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;</center></h3><br>
  <center><input type="submit" value="Save" style=" background-color: #0000A0; color:#FFFFFF" ></center>
   <br><b><center>&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp  &nbsp &nbsp &nbsp &nbsp
 &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp 
 
 <a href="login.php">GO BACK</a></center></b>